// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQETy0K9fss35mLyfzS2GAsxuAVPNljTQ',
    appId: '1:1031888916107:web:c5d70cc97bac956be14e8e',
    messagingSenderId: '1031888916107',
    projectId: 'getxauthenticaton-flutter',
    authDomain: 'getxauthenticaton-flutter.firebaseapp.com',
    storageBucket: 'getxauthenticaton-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLlC76x6414koNRHHf2Da28wSy3Wp1vo',
    appId: '1:1031888916107:android:7e594b3cb75c252de14e8e',
    messagingSenderId: '1031888916107',
    projectId: 'getxauthenticaton-flutter',
    storageBucket: 'getxauthenticaton-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBHlZZrAxfvLQnRGz-dYdxD9pIwI55vgU',
    appId: '1:1031888916107:ios:57bf46a1f826aff5e14e8e',
    messagingSenderId: '1031888916107',
    projectId: 'getxauthenticaton-flutter',
    storageBucket: 'getxauthenticaton-flutter.appspot.com',
    iosClientId: '1031888916107-aijovoalhljjt7r368g313jrbucapjvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGetxapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBHlZZrAxfvLQnRGz-dYdxD9pIwI55vgU',
    appId: '1:1031888916107:ios:57bf46a1f826aff5e14e8e',
    messagingSenderId: '1031888916107',
    projectId: 'getxauthenticaton-flutter',
    storageBucket: 'getxauthenticaton-flutter.appspot.com',
    iosClientId: '1031888916107-aijovoalhljjt7r368g313jrbucapjvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginGetxapp',
  );
}
