// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPCIZYl0MdhufVYkw8L3DkqWCdKGUNEk',
    appId: '1:145691376106:web:620f85aec98a7f25185a93',
    messagingSenderId: '145691376106',
    projectId: 'firebase-crud-islemler',
    authDomain: 'fir-crud-islemler.firebaseapp.com',
    storageBucket: 'firebase-crud-islemler.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AHjgKRh0c2pUhJUVJPk33Dbnl0lglvE',
    appId: '1:145691376106:android:800126b2b014d555185a93',
    messagingSenderId: '145691376106',
    projectId: 'firebase-crud-islemler',
    storageBucket: 'firebase-crud-islemler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7UMDaNCinvS4JZ6P3T4JjrQ4xLzSni6M',
    appId: '1:145691376106:ios:62b63bf8ee628bd9185a93',
    messagingSenderId: '145691376106',
    projectId: 'firebase-crud-islemler',
    storageBucket: 'firebase-crud-islemler.appspot.com',
    iosClientId: '145691376106-fglqjjspb1ds9fmre09a0ctbtj6p7csm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrudIslemler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7UMDaNCinvS4JZ6P3T4JjrQ4xLzSni6M',
    appId: '1:145691376106:ios:62b63bf8ee628bd9185a93',
    messagingSenderId: '145691376106',
    projectId: 'firebase-crud-islemler',
    storageBucket: 'firebase-crud-islemler.appspot.com',
    iosClientId: '145691376106-fglqjjspb1ds9fmre09a0ctbtj6p7csm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrudIslemler',
  );
}
